feat(STOCK-20) add candles request
vladdossik/lissa-trading-tinkoff-api-service pull request #13
Opened 2024-10-27 16:34 UTC by kenpxrk1

Добавил асинхронную логику для получения свечей и метод в Internal контроллере для микросервиса аналитики

2024-10-27 18:27 UTC, SashaTyutyaev approved these changes

2024-10-27 22:27 UTC, Belaquaa requested changes

2024-10-27 22:27 UTC, Belaquaa commented on src/main/java/lissa/trading/tinkoff/stock/service/dto/stock/TinkoffCandlesRequestDto.java
> +    private OffsetDateTime from;
я бы сделал dateTo и dateFrom (или что-то в таком же духе), а то потом ваще непонятно будет, что за переменные

2024-10-27 22:27 UTC, Belaquaa commented on src/main/java/lissa/trading/tinkoff/stock/service/service/stock/TinkoffStockService.java
> +                .collect(Collectors.toList()))
В java > v.8 можно использовать просто toList

2024-10-27 22:27 UTC, Belaquaa commented on src/main/java/lissa/trading/tinkoff/stock/service/service/stock/TinkoffStockService.java
> +                        calculateStockPrice(historicCandle.getOpen().getNano(), historicCandle.getOpen().getUnits()),
будто можно все вынести в отдельный метод

```

private Candle mapToCandle(HistoricCandle historicCandle) {
    return new Candle(
            historicCandle.getVolume(),
            calculateStockPrice(historicCandle.getOpen().getNano(), historicCandle.getOpen().getUnits()),
            calculateStockPrice(historicCandle.getClose().getNano(), historicCandle.getClose().getUnits()),
            calculateStockPrice(historicCandle.getHigh().getNano(), historicCandle.getHigh().getUnits()),
            calculateStockPrice(historicCandle.getLow().getNano(), historicCandle.getLow().getUnits()),
            OffsetDateTime.ofInstant(
                    Instant.ofEpochSecond(
                            historicCandle.getTime().getSeconds(),
                            historicCandle.getTime().getNanos()
                    ),
                    ZoneOffset.UTC
            ),
            historicCandle.getIsComplete()
    );
}
```
И тогда все красивенько и кратенько получится в этом методе

2024-10-27 22:27 UTC, Belaquaa commented on src/main/java/lissa/trading/tinkoff/stock/service/service/AsyncTinkoffService.java
> +                            "from T-Bank: " + ex.getMessage()));
а зачем здесь +?
можно просто перенести на след. строку

2024-10-28 04:52 UTC, vladdossik approved these changes

2024-10-28 04:52 UTC, vladdossik commented on src/main/java/lissa/trading/tinkoff/stock/service/dto/stock/TinkoffCandlesRequestDto.java
> +    private OffsetDateTime from;
так это по идее модельки из тинькофф апи
ты не можешь им имена поменять

2024-10-28 16:46 UTC, kenpxrk1 commented on src/main/java/lissa/trading/tinkoff/stock/service/service/stock/TinkoffStockService.java
> +                .collect(Collectors.toList()))
Все верно, но не с CompletableFuture

2024-10-29 06:02 UTC, vladdossik approved these changes

2024-10-29 15:49 UTC, Belaquaa commented on src/main/java/lissa/trading/tinkoff/stock/service/service/stock/TinkoffStockService.java
> +                .collect(Collectors.toList()))
У меня же все методы с .toList() работают

2024-10-29 15:49 UTC, Belaquaa commented on src/main/java/lissa/trading/tinkoff/stock/service/service/stock/TinkoffStockService.java
> +                .collect(Collectors.toList()))
Разве что это работает с 16 джавы, верно

у нас 17 на проекте

2024-11-01 10:46 UTC, merged